### PR TITLE
Added 3 new methods from HRA API 0.10

### PR DESCRIPTION
**Pull request by andreasbueckle**

### CODE REVIEW

**Comment by andreasbueckle** [comment]
@bherr2 
Can keep branch, still need to work on HuBMAP API client.

**Comment by bherr2** [comment]
Ok! I converted it to a draft. When you feel it's ready to be reviewed and merged just press the "Ready for review" button. Thanks!

**Comment by andreasbueckle** [comment]
Will do.

**Comment by andreasbueckle** [comment]
@bherr2 
I made one more commit to pip install packages at the beginning of hra-api-client-usecase.ipynb

**Comment by andreasbueckle** [comment]
@bherr2 
Those 3 new methods are added and I made another change to make the installation of the client easier. Approve?

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
