### PR TITLE
Python notebooks and additional fixes

### PR DESCRIPTION
**Pull request by axdanbol**
Fixes:
- https://github.com/x-atlas-consortia/hra-api/tree/python-notebooks/notebooks#running-sparql-query-returns-only-a-list-with-values-head-results

Still investigating:
- https://github.com/x-atlas-consortia/hra-api/tree/python-notebooks/notebooks#given-a-spatialentity-already-placed-relative-to-a-reference-spatialentity-retrieve-a-new-direct-spatialplacement-to-the-given-spatialentity-iri
- https://github.com/x-atlas-consortia/hra-api/tree/python-notebooks/notebooks#scene-parameter-ontology_terms-does-not-filter-out-organs

### CODE REVIEW

**Comment by andreasbueckle** [comment]
@axdanbol helped me build the new version of the API and the Python client locally, then I re-ran and marked more cells off as checked. Still remaining issues: https://github.com/x-atlas-consortia/hra-api/blob/python-notebooks/notebooks/README.md

**Comment by andreasbueckle** [comment]
PS: I fixed some more cells (exporting data in https://github.com/x-atlas-consortia/hra-api/blob/python-notebooks/notebooks/hra-api-client-usecase.ipynb) but need to finalize the export code in https://github.com/x-atlas-consortia/hra-api/blob/python-notebooks/notebooks/hra-api-client-usecase.ipynb. The remaining issues are captured here: https://github.com/x-atlas-consortia/hra-api/blob/python-notebooks/notebooks/README.md

**Comment by bherr2** [comment]
Q: "scene parameter ontology_terms does not filter out organs?" A: yes this is expected behavior

**Comment by andreasbueckle** [comment]
Thanks @bherr2, I updated the README.

**Comment by bherr2** [comment]
Q: "Given a SpatialEntity already placed relative to a reference SpatialEntity retrieve a new direct SpatialPlacement to the given SpatialEntity IRI" A: the 404 is an expected output. Will need to investigate further whether the specific input should be giving that output.

**Comment by andreasbueckle** [comment]
In the code, we use `"target_iri": "http://purl.org/ccf/latest/ccf.owl#VHFemale"` as the target IRI. The IRI does not specify a target organ. Could that be the issue why no path can be found?

**Comment by andreasbueckle** [comment]
PS: The example that the HRA API documentation provides (that also gives 404) is:
```
{
  "target_iri": "http://purl.org/ccf/latest/ccf.owl#VHFemale",
  "rui_location": {
    "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",
    "@id": "http://purl.org/ccf/1.5/f7130161-ad0a-4801-b5a4-f6297e0f1869",
    "@type": "SpatialEntity",
    "creator": "Bruce Herr",
    "creator_first_name": "Bruce",
    "creator_last_name": "Herr",
    "creation_date": "2022-04-27",
    "ccf_annotations": [
      "http://purl.obolibrary.org/obo/UBERON_0002015",
      "http://purl.obolibrary.org/obo/UBERON_0000362",
      "http://purl.obolibrary.org/obo/UBERON_0004200",
      "http://purl.obolibrary.org/obo/UBERON_0001225",
      "http://purl.obolibrary.org/obo/UBERON_0001284",
      "http://purl.obolibrary.org/obo/UBERON_0002189"
    ],
    "x_dimension": 11,
    "y_dimension": 12,
    "z_dimension": 13,
    "dimension_units": "millimeter",
    "placement": {
      "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",
      "@id": "http://purl.org/ccf/1.5/f7130161-ad0a-4801-b5a4-f6297e0f1869_placement",
      "@type": "SpatialPlacement",
      "target": "http://purl.org/ccf/latest/ccf.owl#VHFLeftKidneyV1.1",
      "placement_date": "2022-04-27",
      "x_scaling": 1,
      "y_scaling": 1,
      "z_scaling": 1,
      "scaling_units": "ratio",
      "x_rotation": -61,
      "y_rotation": 50,
      "z_rotation": -84,
      "rotation_order": "XYZ",
      "rotation_units": "degree",
      "x_translation": 20.149,
      "y_translation": 109.963,
      "z_translation": 38.79,
      "translation_units": "millimeter"
    }
  }
}
```

**Review by bherr2 — APPROVED** [review]

**Comment by bherr2** [comment]
Merging,  feel free to create another PR if you have more fixes/updates.

**Comment by andreasbueckle** [comment]
Thanks! I still need to fix the export in the usecase notebook but need to focus on another notebook for hra-pop for now. Will get back to this.

**Comment by andreasbueckle** [comment]
New PR draft here: https://github.com/x-atlas-consortia/hra-api/pull/14

**Pull request merged**
